name: GQL Schema - Breaking Changes Labeler
on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    needs: compare_schema
    if: ${{ failure() }}
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Has GQL Schema Change (Breaking)
          github_token: ${{ github.token }}

  compare_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Compare Schema
        run: |
          echo "::set-output name=compare-schema::$(bin/rake graphql:schema:compare)\n"
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{join(steps.compare_schema.outputs.*, '\n')}
            })
